all:
	docker build --no-cache -t CarlitoCepillo/pybd_movie_project .

fast:
	docker build -t CarlitoCepillo/pybd_movie_project .

install:
	docker login
	docker push CarlitoCepillo/pybd_movie_project
